### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by dorianim** [fschuett/oss-linbo#1]
Hi @fschuett 

I started to configure a buildroot linbo from scratch based on your work over here (https://github.com/CodeCrafter912/linuxmuster-linbo7-buildroot) the long-term goal is to get the official linuxmuster linbo to buildroot. There is not a lot yet, I'm still starting to figure some things out ;)

Personally, I don't know you, but I like the work you've done here. I have some questions though:
- What exactly is oss?
- Have implemented cool new features into linbo_cmd?
- Are you willing to get the two projects together again in order to benefit from each others work? Now where Linuxmuster wants to switch to buildroot two, this might make more sense than ever before :)

Regards,
Dorian

**Comment by fschuett** [comment]
Hallo @CodeCrafter912 Dorian,

the continues development of linuxmuster-linbo did help me for years now, so I am happy if I can help in the transition to buildroot.

- OSS (Open school server), recently renamed to Cranix(https://wiki.cephalix.eu/index.php/Hauptseite) is similar to linuxmuster a linux based school server.
- I did not implement cool features but invested a lot of time to keep oss-linbo as close as possible to linuxmuster-linbo, while I simplified the build system to make it manageable by me.
- I would love to see the two projects together again. linuxmuster can benefit by taking away the burden to configure kernel and a lot of packages and at the same time stay in charge of every configuration step and get the gain of always access to new kernel versions and all other recent versions for all other packages. Additionally buildroot is independent of the underlying system because it builds completely on it's own.

That said, here is an entry point.
In the branch merge-oss-lmn of linuxmuster-linbo I have from time to time synced back my build system. Have a look at that branch.
I included buildroot by means of "subtree" feature of git. From time to time I check in a new release of buildroot in a single commit. In this way I have a stable build system and my git log becomes not too crouded. A description of a release change is in the file rpm/README.md.
I build rpm packages from that directory by means of oss-linbo.spec. For the build process I use a Makefile rpm/Makefile. This is a good starting point. It is quite short and shows how much work is done by buildroot.
Buildroot can be configured by a directory system, which exists below buildroot-external.
For GUI I do use linbo_gui-2.0, while linuxmuster-linbo used linbo_gui-1.0. The second directory can now be deleted since it is no longer used by you.
For oss-linbo I don't use conf, linbo_gui-1.0, patches, toolchain, debian. The eclipse, test subdirs are just for me to debug linbo_cmd in a test environment, because debugging bash scripts is sometimes tedious.

One major difference is, that I did not use differrent paths for linbo6, linbo7 and oss-linbo but introduced a flag FLAVOUR=oss|lmn6|lmn7.
Wherever possible I merged the files with if/then/else. When the differences were too big to merge, I used three files *.oss, *.lmn6, *.lmn7 and during build time the correct file is chosen. You will find this kind of logic in the debian build dir.

I always wanted to created branches for the three versions, f.ex. linbo6, linbo7, oss. That would make it easier to maintain differences and to merge fixes to the versions. That would simplify the branches and help keeping track of the differences and have only that files in the branch, that are needed.

I stopped merging current state of linuxmuster-linbo to my repo because I did not split away the gui and will need some kind of logic to keep it local, while not conflicting with code to download it.

Since some time I don't have write access to the repo any more, so I create a pull request to merge my current state back to merge-oss-lmn.

Bye, Frank

**Comment by fschuett** [comment]
Hi Dorian,

Well I cannot easily create a pull request.

As a starting point for you to use buildroot:
Copy from oss-linbo/merge-oss-lmn.
Use the directories buildroot, buildroot-external, the linbo dirs like etc, linbo, linbofs, share, the debian subdir and the files in the main directory.
Then try to use rpm/Makefile and the "%make" section of rpm/oss-linbo.spec and merge these to the debian Makefile. This should leave you with a buildroot version of the debian package.

Get back to me if there are any problems.

Good luck.

**Comment by dorianim** [comment]
Hi Frank,

Thanks for all this information :)
Currently, I am trying to build just linbo (the linbofs.lz file) using buildroot. All the server side Scripts will follow later. I was able to do so, by copying some of you packages and configuration into by buildroot tree. I am taking a slightly different approach regarding the folder structure, but the result is the same. 
I was able to build everythng but host-ubuntugrub. Do I need that when building on an Ubuntu system?
I tried to boot with my seemingly successfull build, but I ran into a kernel panic:
![image](https://user-images.githubusercontent.com/30153207/116738861-4e419500-a9f3-11eb-8931-8ca11aaa15f8.png)

Do you know how to troubleshoot this? Is it a problem that I am building on Ubuntu 20.04 rather than 18.04?

Thanks for your help! :D

Rgards,
Dorian

**Comment by fschuett** [comment]
Hallo Dorian,
Am Freitag, 30. April 2021, 20:34:45 CEST schrieb Dorian Zedler:
> Thanks for all this information :)
> Currently, I am trying to build just linbo (the linbofs.lz file) using
> buildroot. All the server side Scripts will follow later. I was able to do
> so, by copying some of you packages and configuration into by buildroot
> tree. I am taking a slightly different approach regarding the folder
> structure, but the result is the same.
I hope you keep buildroot and buildroot-external separate. That is necessary
to easily adapt to new buildroot versions while being able to keep buidroot
stable for a while.

> I was able to build everythng but
> host-ubuntugrub. Do I need that when building on an Ubuntu system? I tried
This is strange, I was able to build host-ubuntugrub even on an opensuse 
system. buildroot is autark, it builds everything by itself.
Maybe you missed something.

> to boot with my seemingly successfull build, but I ran into a kernel panic:
> ![image](https://user-images.githubusercontent.com/30153207/116738861-4e419
> 500-a9f3-11eb-8931-8ca11aaa15f8.png)
> 
> Do you know how to troubleshoot this? Is it a problem that I am building on
> Ubuntu 20.04 rather than 18.04?
What kernel configuration did you use. You should start with my kernel config 
and adapt to the one in conf, that linuxmuster uses.
Sounds to me like your kernel is not understanding the compression format of 
the initrd file.

Bye, Frank

**Comment by dorianim** [comment]
> I hope you keep buildroot and buildroot-external separate. That is necessary
to easily adapt to new buildroot versions while being able to keep buidroot
stable for a while.

Don't worry, I have already worked with buildroot, for example over here:
https://github.com/CodeCrafter912/cwa-qr-code-generator-os/tree/v1.0.1
Until now, I just used it for Raspberry Pis, though. You can see everything I did so far over here:
https://github.com/CodeCrafter912/linuxmuster-linbo7-buildroot

> This is strange, I was able to build host-ubuntugrub even on an opensuse
system. buildroot is autark, it builds everything by itself.
Maybe you missed something.

Where did you get that package from? Did you create it yourself?

> What kernel configuration did you use.

I use your configuration from here:
https://github.com/fschuett/oss-linbo/blob/merge-oss-lmn/buildroot-external/board/linux-x86_64.config

> Sounds to me like your kernel is not understanding the compression format of
the initrd file.

Ok, then I will do some digging :)

Regards,
Dorian

**Comment by dorianim** [comment]
I am so stupid... :sweat_smile: 

I forgot to copy the bzImage in place. That was the reason for the kernel panic. Now it boots :)

**Comment by fschuett** [comment]
I am trying to merge master from linuxmuster-linbo once more.
While I am at it, I notice some differences.
- I did a lot of debugging with UEFI boot, since I do use many netbooks with quite some EFI problems and made the reboot work for linbo, too.

**Comment by dorianim** [comment]
> I did a lot of debugging with UEFI boot, since I do use many netbooks with quite some EFI problems and made the reboot work for linbo, too.

That's cool! Is that what the ms-sys package is for? For writing the efi bootrecord?

**Comment by dorianim** [comment]
By the way, if you want to implement my GUI, it should be as simple as using something like `$(call github,linuxmuster,linuxmuster-linbo-gui,$(LINBO_GUI_VERSION))` as `LINBO_GUI_SITE`. Like this, the GUI will be downloaded from GitHub and built into you linbofs.

**Comment by fschuett** [comment]
> By the way, if you want to implement my GUI, it should be as simple as using something like `$(call github,linuxmuster,linuxmuster-linbo-gui,$(LINBO_GUI_VERSION))` as `LINBO_GUI_SITE`. Like this, the GUI will be downloaded from GitHub and built into you linbofs.

Thank you, I will do that and try that out with merged linbo-2.4, when Abitur is over.

**Comment by fschuett** [comment]
> > I did a lot of debugging with UEFI boot, since I do use many netbooks with quite some EFI problems and made the reboot work for linbo, too.
> 
> That's cool! Is that what the ms-sys package is for? For writing the efi bootrecord?

Looks like ms-sys is for booting the system to windows. That is an area I am not working in, since I don't have access to no windows computer at all. I do work on linux as client system only.

When linbo updates itself, sometimes a reboot is done but this reboot used to be not to linbo, I made it reboot to linbo.

**Comment by dorianim** [comment]
Hi Frank,

Unfortunately Thomas Schmitt does not want to do the port anymore. We (all the other devs) are really mad at him, but we don't have the ressouces to do this without his cooperation (we considered to do so). So, unfortunately Linuxmuster Linbo is going to stay as it is for now. Nevertheless, thanks for your help.

And I would still be happy to assist you in getting my new Gui to run in oss-linbo :)

Regards,
Dorian

**Comment by fschuett** [comment]
Hello Dorian,
That is disappointing and I already did invest some days to resync the branches. Well there's nothing to be done about it.
Thank you for trying.
I'll come back to your GUI as soon as I find time to test it out.

Bye,
Frank
